name: Build

env:
  GO_VERSION: '1.16.9'
  IPXE_VERSION: '1.21.1'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache ipxe
      uses: actions/cache@v2
      with:
        path: ipxe
        key: ipxe-v${{ env.IPXE_VERSION }}
      id: cache

    - name: Checkout ipxe
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        path: ipxe
        repository: ipxe/ipxe
        ref: v${{ env.IPXE_VERSION }}

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: go generate ./...
      shell: bash
