name: Build

inputs:
  go_version:
    required: true
  ipxe_version:
    required: true

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '${{ inputs.go_version }}'

    - name: Build dependencies
      run: go generate ./...
      shell: bash

    - name: Build binaries
      env:
        CGO_ENABLED: 0
      run: go build -ldflags="-X 'main.Version=${{ github.ref }}'" -o bin/pixie ./cmd/pixie
      shell: bash
