name: Build

inputs:
  go_version:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout iPXE
      uses: actions/checkout@v2
      with:
        path: ipxe
        repository: ipxe/ipxe
        ref: 70995397e5bdfd3431e12971aa40630c7014785f
        fetch-depth: 0 # we need the entire history to build iPXE

    - name: Add cross-compile deps
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu \
                            gcc-arm-none-eabi

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod

    - name: Go generate
      run: go generate ./...
      shell: bash
