name: Build

inputs:
  go_version:
    required: true
  ipxe_version:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout iPXE
      uses: actions/checkout@v2
      with:
        path: ipxe
        repository: ipxe/ipxe
        ref: v${{ inputs.ipxe_version }}

    - name: Cache iPXE ROMs
      uses: actions/cache@v2
      with:
        path: |
          ipxe/src/bin
          ipxe/src/bin-x86_64-efi
          ipxe/src/bin-i386-efi
        key: ipxe-v${{ inputs.ipxe_version }}
      id: cache

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go_version }}

    - name: Build iPXE ROMs
      run: |
        if [[ "${{ steps.cache.outputs.cache-hit }}" = 'true' ]]; then
          echo "Cache hit, skipping ipxe build"
        else
          go generate ./...
        fi
      shell: bash
