name: Build

env:
  GO_VERSION: '1.16.9'
  IPXE_VERSION: '1.21.1'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout ipxe
      uses: actions/checkout@v2
      with:
        path: ipxe
        repository: ipxe/ipxe
        ref: v${{ env.IPXE_VERSION }}

    - name: Cache ipxe
      uses: actions/cache@v2
      with:
        path: |
          ipxe/src/bin
          ipxe/src/bin-x86_64-efi
          ipxe/src/bin-i386-efi
        key: ipxe-v${{ env.IPXE_VERSION }}
      id: cache

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build dependencies
      run: |
        if [[ "${{ steps.cache.outputs.cache-hit}}" = 'true' ]]; then
          echo "Cache hit, skipping ipxe build"
        else
          go generate ./...
        fi
      shell: bash
