name: Build

inputs:
  go_version:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout iPXE
      uses: actions/checkout@v2
      with:
        path: ipxe
        repository: ipxe/ipxe
        ref: f43c2fd69749bb9a44f2a3ab61b6735938432b52
        fetch-depth: 0 # we need the entire history to build iPXE

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go_version }}

    - name: Go generate
      run: go generate ./...
      shell: bash
