name: Get version

inputs:
  path:
    default: .

runs:
  using: composite
  steps:
    - name: Get commit sha
      shell: bash
      run: |
        echo "::set-output name=full::$(git -C '${{ inputs.path }}' rev-parse HEAD)"
        echo "::set-output name=short::$(git -C '${{ inputs.path }}' rev-parse --short HEAD)"
      id: sha

    - name: Get tag
      shell: bash
      run: |
        VERSION="${GITHUB_REF#refs/tags/}"
        VERSION_MAJOR="${VERSION%%\.*}"
        VERSION_MINOR="${VERSION%.*}"
        echo "::set-output name=major::$VERSION_MAJOR"
        echo "::set-output name=minor::$VERSION_MINOR"
        echo "::set-output name=patch::$VERSION"
      id: tag

outputs:
  tag-major:
    value: ${{ steps.tag.outputs.major }}
  tag-minor:
    value: ${{ steps.tag.outputs.minor }}
  tag-patch:
    value: ${{ steps.tag.outputs.patch }}
  sha:
    value: ${{ steps.sha.outputs.full }}
  sha-short:
    value: ${{ steps.sha.outputs.short }}
