name: Create artifact

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

env:
  IPXE_VERSION: '1.21.1'
  GO_VERSION: '1.16.9'

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache ipxe
        uses: actions/cache@v2
        with:
          path: ipxe
          key: ipxe-v${{ env.IPXE_VERSION }}
        id: cache

      - name: Checkout ipxe
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          path: ipxe
          repository: ipxe/ipxe
          ref: v${{ env.IPXE_VERSION }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: go generate ./...

      - name: Get short commit sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        id: sha

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=dev-${{ steps.sha.outputs.sha_short }}'" -o bin/pixie ./cmd/pixie

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pixie-${{ steps.sha.outputs.sha_short }}
          path: bin/
