name: Create artifact

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout ipxe
        uses: actions/checkout@v2
        with:
          repository: ipxe/ipxe
          ref: v1.21.1

      - name: Build
        uses: p3lim/pixie@master
        with:
          go_version: '1.17.2'

      - name: Get short commit sha
        run: echo "::set-output name=sha_short::$(git rev-parse --shot HEAD)"
        id: sha

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pixie-${{ steps.sha.outputs.sha_short }}
          path: bin/
