name: Create artifact

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  prepare:
    uses: ./.github/workflows/reusable/prep.yaml
  ipxe:
    uses: ./.github/workflows/reusable/ipxe.yaml

  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Get short commit sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        id: sha

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=dev-${{ steps.sha.outputs.sha_short }}'" -o bin/pixie ./cmd/pixie

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pixie-${{ steps.sha.outputs.sha_short }}
          path: bin/
