name: Create artifact

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout ipxe
        uses: actions/checkout@v2
        with:
          repository: ipxe/ipxe
          ref: v1.21.1

      - run: tree

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.9'

      - name: Build dependencies
        env:
          GO111MODULE: auto
        run: go generate ./pkg/tftp

      - name: Build binaries
        env:
          GO111MODULE: auto
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=${{ github.ref }}'" -o bin/pixie ./cmd/pixie

      - name: Get short commit sha
        run: echo "::set-output name=sha_short::$(git rev-parse --shot HEAD)"
        id: sha

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pixie-${{ steps.sha.outputs.sha_short }}
          path: bin/
