name: Build iPXE

on:
  workflow_call:

runs:
  uses: composite
  steps:
    - name: Checkout iPXE
      uses: actions/checkout@v2
      with:
        path: ipxe
        repository: ipxe/ipxe
        ref: 70995397e5bdfd3431e12971aa40630c7014785f
        fetch-depth: 0 # we need the entire history to build iPXE

    - name: Build iPXE
      run: go generate ./...
      shell: bash
