name: Create package

on:
  push:
    tags:
      - '**'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: p3lim/pixie@master
        with:
          go_version: '1.16.9'
          ipxe_version: '1.21.1'

      - name: Parse semantic version
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
        id: version

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=${{ steps.version.outputs.fullversion }}'" -o bin/pixie ./cmd/pixie

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile
          image: pixie
          tags: ${{ steps.version.outputs.fullversion }} ${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }} ${{ steps.version.outputs.major }} ${{ github.sha }} latest
        id: image

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.image.outputs.image }}
          tags: ${{ steps.image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
