name: Create package

on:
  push:
    tags:
      - '**'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: p3lim/pixie@master

      - name: Get version
        uses: ./.github/actions/version
        id: version

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=${{ steps.tag.outputs.tag-patch }}'" -o bin/pixie ./cmd/pixie

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile
          image: pixie
          tags: ${{ steps.tag.outputs.tag-major }} ${{ steps.tag.outputs.tag-minor }} ${{ steps.tag.outputs.tag-patch }} ${{ steps.tag.outputs.sha }} latest
        id: image

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.image.outputs.image }}
          tags: ${{ steps.image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
