name: Create package

on:
  push:
    tags:
      - '**'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: p3lim/pixie@master

      - name: Get tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION_MAJOR="${VERSION%%\.*}"
          VERSION_MINOR="${VERSION%.*}"
          echo "::set-output name=tag::$VERSION"
          echo "::set-output name=major::$VERSION_MAJOR"
          echo "::set-output name=minor::$VERSION_MINOR"
        id: tag

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=${{ steps.tag.outputs.tag }}'" -o bin/pixie ./cmd/pixie

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile
          image: pixie
          tags: ${{ steps.tag.outputs.tag }} ${{ steps.tag.outputs.major }} ${{ steps.tag.outputs.minor }} ${{ github.sha }} latest
        id: image

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.image.outputs.image }}
          tags: ${{ steps.image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
