name: Create release

on:
  push:
    tags:
      - '**'

jobs:
  build-ipxe:
    uses: ./.github/workflows/ipxe_build.yaml

  release:
    runs-on: ubuntu-latest
    needs:
      - build-ipxe
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Restore iPXE ROMs from artifact
        uses: actions/download-artifact@v3
        with:
          name: ipxe-roms
          path: pkg/tftp/ipxe

      - name: Get version
        uses: ./.github/actions/version
        id: version

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=${{ steps.version.outputs.tag-patch }}'" -o bin/pixie ./cmd/pixie

      - name: Trim changelog
        run: sed -ni '1p;2,/^###/{/^###/q;p;}' CHANGELOG.md

      - uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: bin/pixie
