name: Create build from latest commit

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  build-ipxe:
    uses: ./.github/workflows/ipxe_build.yaml

  latest:
    runs-on: ubuntu-latest
    needs:
      - build-ipxe
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Restore iPXE ROMs from artifact
        uses: actions/download-artifact@v3
        with:
          name: ipxe-roms
          path: pkg/tftp/ipxe

      - name: Get version
        uses: ./.github/actions/version
        id: version

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=dev-${{ steps.version.outputs.sha-short }}'" -o bin/pixie ./cmd/pixie

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pixie-${{ steps.version.outputs.sha-short }}
          path: bin/
