name: Create container image

on:
  push:
    tags:
      - '**'

jobs:
  build-ipxe:
    uses: ./.github/workflows/ipxe_build.yaml

  image:
    runs-on: ubuntu-latest
    needs:
      - build-ipxe
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Restore iPXE ROMs from artifact
        uses: actions/download-artifact@v3
        with:
          name: ipxe-roms
          path: pkg/tftp/ipxe

      - name: Get version
        uses: ./.github/actions/version
        id: version

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=${{ steps.tag.outputs.tag-patch }}'" -o bin/pixie ./cmd/pixie

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile
          image: pixie
          tags: ${{ steps.tag.outputs.tag-major }} ${{ steps.tag.outputs.tag-minor }} ${{ steps.tag.outputs.tag-patch }} ${{ steps.tag.outputs.sha }} latest
        id: image

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.image.outputs.image }}
          tags: ${{ steps.image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
