name: Create release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ${{ github.action_path }}/go.yaml
      - uses: ${{ github.action_path }}/ipxe.yaml

      - name: Get tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION_MAJOR="${VERSION%%\.*}"
          VERSION_MINOR="${VERSION%.*}"
          echo "::set-output name=tag::$VERSION"
          echo "::set-output name=major::$VERSION_MAJOR"
          echo "::set-output name=minor::$VERSION_MINOR"
        id: tag

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=${{ steps.tag.outputs.tag }}'" -o bin/pixie ./cmd/pixie

      - name: Trim changelog
        run: sed -ni '1p;2,/^###/{/^###/q;p;}' CHANGELOG.md

      - uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: bin/pixie
