name: Create release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: p3lim/pixie@master
        with:
          go_version: '1.16.9'
          ipxe_version: '1.21.1'

      - name: Get tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION_MAJOR="${VERSION%%\.*}"
          VERSION_MINOR="${VERSION%.*}"
          echo "::set-output name=tag::$VERSION"
          echo "::set-output name=major::$VERSION_MAJOR"
          echo "::set-output name=minor::$VERSION_MINOR"
        id: tag

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=${{ steps.tag.outputs.tag }}'" -o bin/pixie ./cmd/pixie

      - uses: softprops/action-gh-release@v1
        with:
          # TODO: changelog
          # body_path: CHANGELOG.txt
          files: bin/pixie
