name: Create release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: p3lim/pixie@master

      - name: Get version
        uses: ./.github/actions/version
        id: version

      - name: Build binaries
        env:
          CGO_ENABLED: 0
        run: go build -ldflags="-X 'main.Version=${{ steps.version.outputs.patch }}'" -o bin/pixie ./cmd/pixie

      - name: Trim changelog
        run: sed -ni '1p;2,/^###/{/^###/q;p;}' CHANGELOG.md

      - uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: bin/pixie
