name: Create release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: p3lim/pixie@master
        with:
          go_version: '1.16.9'
          ipxe_version: '1.21.1'

      - uses: softprops/action-gh-release@v1
        with:
          # TODO: changelog
          # body_path: CHANGELOG.txt
          files: bin/pixie
